### ISSUE TITLE
这么过分一定要记录下来

### ISSUE THREAD

**Issue by guokailu** [NeWive/UniChatFrontEnd#7]
进行electron打包时，自动安装是不太行便选择了手动安装。但是npm install electron真的安装的太慢太慢了，每次都卡到node.js页面。网上说是直接关闭重新下载即可，but每次都一样，或者就报错 cannot find node/module/cli.js 。查看文件目录貌似还真没有cli.js。一气之下便重新安装了node.js并且也更改了electron下载源。在~/.npmrc 文件输入
registry=https://registry.npm.taobao.org
electron_mirror="https://npm.taobao.org/mirrors/electron/
重安之后就可以成功安装electron。据说还可能是node.js与electron版本不匹配造成，还是直接重装比较好，最新的node自带npm。麻麻再也不用担心下载慢了

**Comment by Cherrison** [comment]
有时它还需要 安装系统依赖。 `sudo apt-get install -f` 可以自动修复
