### ISSUE TITLE
待解决的问题，前端

### ISSUE THREAD

**Issue by guokailu** [NeWive/UniChatFrontEnd#8]
加好友以及频道页面未作，窗口大小与页面不统一，放大缩小时会出现空白区，需要进一步学习完善。窗体默认菜单栏需要去掉并且将功能帮到自定义的控件上

**Comment by NeWive** [comment]
加好友以及频道页面UI周五初稿，预计周六完成加好友和频道的基本逻辑

**Comment by NeWive** [comment]
完成添加好友以及添加频道的弹出层逻辑，开始绑接口

**Comment by guokailu** [comment]
> 完成添加好友以及添加频道的弹出层逻辑，开始绑接口

好哒
